stack: go 1.10
clone_folder: c:\gopath\src\github.com\kung-foo\certgrep
environment:
  GOPATH: c:\gopath
install:
  - cinst 7zip.commandline
  - cinst winpcap
  - appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_4_1_3.zip
  - 7za x .\WpdPack_4_1_3.zip -oc:\
build_script:
  - go build -o dist\certgrep.exe cmd\certgrep\main.go
