os: Windows Server 2012 R2
stack: go 1.10

clone_folder: c:\gopath\src\github.com\kung-foo\certgrep

install:
  - cinst 7zip.commandline
  - cinst winpcap
  - ps: >-
      if(!(Test-Path "C:\tools\mingw64\bin\gcc.exe")) {
        cinst mingw > mingw-install.txt
        Push-AppveyorArtifact mingw-install.txt
      }
  - ps: >-
      if(!(Test-Path "C:\WpdPack\Lib\wpcap.lib")) {
        appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
        7za x .\WpdPack_4_1_2.zip -oc:\
      }
  - set PATH=C:\tools\mingw64\bin;%GOROOT%\bin;%PATH%

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\tools\mingw64 -> appveyor.yml
  - C:\WpdPack -> appveyor.yml

environment:
  GOPATH: c:\gopath

build_script:
  - go build -o dist\certgrep.exe cmd\certgrep\main.go

artifacts:
  - path: dist\certgrep.exe
    name: certgrep.exe

deploy:
  - provider: GitHub
    artifact: certgrep.exe
    draft: true
    prerelease: true
    auth_token:
      secure: dIvC4xTGEs21nwPgR07mAwG5aNoSJKVzeGdS0TTrHcfB8BoKQPCA+0LgGr9lSuXP
    # on:
    #   branch: master                # release from master branch only
    #   appveyor_repo_tag: true       # deploy on tag push only
